from collections.abc import Callable
from typing import Any

def ratio(s1: Any, s2: Any, *, processor: Callable[[Any], Any] | None = None, score_cutoff: float | None = None) -> float: ...
def partial_ratio(s1: Any, s2: Any, *, processor: Callable[[Any], Any] | None = None, score_cutoff: float | None = None) -> float: ...
def partial_ratio_alignment(s1: Any, s2: Any, *, processor: Callable[[Any], Any] | None = None, score_cutoff: float | None = None) -> Any: ...
def token_sort_ratio(s1: Any, s2: Any, *, processor: Callable[[Any], Any] | None = None, score_cutoff: float | None = None) -> float: ...
def token_set_ratio(s1: Any, s2: Any, *, processor: Callable[[Any], Any] | None = None, score_cutoff: float | None = None) -> float: ...
def token_ratio(s1: Any, s2: Any, *, processor: Callable[[Any], Any] | None = None, score_cutoff: float | None = None) -> float: ...
def partial_token_sort_ratio(s1: Any, s2: Any, *, processor: Callable[[Any], Any] | None = None, score_cutoff: float | None = None) -> float: ...
def partial_token_set_ratio(s1: Any, s2: Any, *, processor: Callable[[Any], Any] | None = None, score_cutoff: float | None = None) -> float: ...
def partial_token_ratio(s1: Any, s2: Any, *, processor: Callable[[Any], Any] | None = None, score_cutoff: float | None = None) -> float: ...
def WRatio(s1: Any, s2: Any, *, processor: Callable[[Any], Any] | None = None, score_cutoff: float | None = None) -> float: ...
def QRatio(s1: Any, s2: Any, *, processor: Callable[[Any], Any] | None = None, score_cutoff: float | None = None) -> float: ...
