"""Type stubs for rustfuzz.search module."""

from collections.abc import Iterable
from typing import Any


class BM25:
    """BM25Okapi full-text search index."""

    def __init__(self, corpus: Iterable[str], k1: float = 1.5, b: float = 0.75) -> None: ...

    @property
    def num_docs(self) -> int: ...

    def get_scores(self, query: str) -> list[float]: ...
    def get_top_n(self, query: str, n: int = 5) -> list[tuple[str, float]]: ...
    def get_batch_scores(self, queries: Iterable[str]) -> list[list[float]]: ...
    def get_top_n_fuzzy(self, query: str, n: int = 5, bm25_candidates: int = 50, fuzzy_weight: float = 0.3) -> list[tuple[str, float]]: ...
    def get_top_n_rrf(self, query: str, n: int = 5, bm25_candidates: int = 100, rrf_k: int = 60) -> list[tuple[str, float]]: ...
    def fuzzy_only(self, query: str, n: int = 5) -> list[tuple[str, float]]: ...


class HybridSearch:
    """Tier-3 Semantic Hybrid Search framework combining BM25 with vector search via RRF."""

    def __init__(self, corpus: Iterable[str], embeddings: Any = None, k1: float = 1.5, b: float = 0.75) -> None: ...

    @property
    def has_vectors(self) -> bool: ...

    def search(self, query: str, query_embedding: Any = None, n: int = 5, rrf_k: int = 60) -> list[tuple[str, float]]: ...
