from collections.abc import Callable
from typing import Any

def distance(s1: Any, s2: Any, *, open_penalty: float = 1.0, extend_penalty: float = 0.5, processor: Callable[..., Any] | None = None, score_cutoff: float | None = None) -> float: ...
def similarity(s1: Any, s2: Any, *, open_penalty: float = 1.0, extend_penalty: float = 0.5, processor: Callable[..., Any] | None = None, score_cutoff: float | None = None) -> float: ...
def normalized_distance(s1: Any, s2: Any, *, open_penalty: float = 1.0, extend_penalty: float = 0.5, processor: Callable[..., Any] | None = None, score_cutoff: float | None = None) -> float: ...
def normalized_similarity(s1: Any, s2: Any, *, open_penalty: float = 1.0, extend_penalty: float = 0.5, processor: Callable[..., Any] | None = None, score_cutoff: float | None = None) -> float: ...
